services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file: .env
    volumes:
      - ./:/var/app
    ports:
      - "8080:8080"
    depends_on:
      - database
    command: /bin/sh -c "go mod download && dockerize -timeout 60s -wait tcp://database:3306 && air -c .air.toml"
  database:
    image: mysql:5.7
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "auth_api"
      TZ: "Asia/Tokyo"
    ports:
      - "13306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
