name: Build

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Cache dependencies
        uses: actions/cache@v3
        id: backend_cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.OS }}-1.19-${{ hashFiles('**/go.sum') }}

      - name: Get dependencies
        if: ${{ steps.backend_cache.outputs.cache-hit != 'true' }}
        run: go mod download

      - name: Run vet
        run: go vet ./...

      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1
        with:
          version: 2022.1.2
          install-go: false
          cache-key: auth-api

      - name: Run hadolint
        uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: Dockerfile

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Cache dependencies
        uses: actions/cache@v3
        id: backend_cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.OS }}-1.19-${{ hashFiles('**/go.sum') }}

      - name: Get dependencies
        if: ${{ steps.backend_cache.outputs.cache-hit != 'true' }}
        run: go mod download

      - name: Run test
        env:
          GIN_MODE: test
        run: go test -v ./...
