name: Build

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      - name: Cache dependencies
        uses: actions/cache@v2
        id: backend_cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.OS }}-${{ hashFiles('**/go.sum') }}

      - name: Get dependencies
        if: ${{ steps.backend_cache.outputs.cache-hit != 'true' }}
        run: go mod download

      - name: Run vet
        run: go vet ./...

      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1
        with:
          version: 2022.1.2
          install-go: false
          cache-key: auth-api

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      - name: Cache dependencies
        uses: actions/cache@v2
        id: backend_cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.OS }}-${{ hashFiles('**/go.sum') }}

      - name: Get dependencies
        if: ${{ steps.backend_cache.outputs.cache-hit != 'true' }}
        run: go mod download

      - name: Run test
        env:
          GIN_MODE: test
        run: go test -v ./...

  build_image:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Build image
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          target: production
          tags: gotoeveryone/auth-api:1.0.0

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Deploy
    needs:
      - build_image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: okteto/login@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - uses: okteto/namespace@latest
        with:
          namespace: gotoeveryone

      - uses: okteto/apply@latest
        with:
          manifest: manifests

  notify_slack:
    if: ${{ always() }}
    needs:
      - deploy
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/workflow-conclusion-action@v1
      - name: Notify to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ env.WORKFLOW_CONCLUSION }}
          author_name: GitHub Actions
          fields: repo,message,author,ref
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.NOTIFY_SLACK_WEBHOOK_URL }}
