name: Deploy

on:
  workflow_dispatch:

jobs:
  build_image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          target: production
          tags: gotoeveryone/auth-api:1.0.0

  deploy:
    name: Deploy
    needs:
      - build_image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: okteto/login@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - uses: okteto/namespace@latest
        with:
          namespace: gotoeveryone

      - uses: okteto/apply@latest
        with:
          manifest: manifests

  notify_slack:
    if: ${{ always() }}
    needs:
      - deploy
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/workflow-conclusion-action@v3
      - name: Notify to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ env.WORKFLOW_CONCLUSION }}
          author_name: GitHub Actions
          fields: repo,message,author,ref
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.NOTIFY_SLACK_WEBHOOK_URL }}
